
version: 2
jobs:
  build:
    working_directory: /go/src/github.com/segmentio/burrow
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - run: go get -v -t ./...
      - run: go vet ./...
      - run: go test -race ./...
      - run:
          command: |
            TAG=`git rev-parse --short HEAD`
            docker build -t segment/burrow:$TAG .
            docker tag segment/burrow:$TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/burrow:$TAG
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/burrow:$TAG
      - store_artifacts:
          path: .run
          destination: trebuchet
